// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWRbk7L_38N8mJfk-U5sXXjb8YiTudPdU',
    appId: '1:184321486815:web:aa56301bea8211dcc25e6a',
    messagingSenderId: '184321486815',
    projectId: 'portfolio-f0840',
    authDomain: 'portfolio-f0840.firebaseapp.com',
    storageBucket: 'portfolio-f0840.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoWlQnLyv3pzUpOGj5ihIwSc2cOKhQu1A',
    appId: '1:184321486815:android:be5c8e63129dcb5fc25e6a',
    messagingSenderId: '184321486815',
    projectId: 'portfolio-f0840',
    storageBucket: 'portfolio-f0840.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1ce2zwkuEV2024RvQU04hCB37pzqUsek',
    appId: '1:184321486815:ios:ef80d31d3117b569c25e6a',
    messagingSenderId: '184321486815',
    projectId: 'portfolio-f0840',
    storageBucket: 'portfolio-f0840.appspot.com',
    iosBundleId: 'com.example.flutterPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1ce2zwkuEV2024RvQU04hCB37pzqUsek',
    appId: '1:184321486815:ios:ef80d31d3117b569c25e6a',
    messagingSenderId: '184321486815',
    projectId: 'portfolio-f0840',
    storageBucket: 'portfolio-f0840.appspot.com',
    iosBundleId: 'com.example.flutterPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWRbk7L_38N8mJfk-U5sXXjb8YiTudPdU',
    appId: '1:184321486815:web:f039b79ad7c5f874c25e6a',
    messagingSenderId: '184321486815',
    projectId: 'portfolio-f0840',
    authDomain: 'portfolio-f0840.firebaseapp.com',
    storageBucket: 'portfolio-f0840.appspot.com',
  );
}
